### ISSUE TITLE
[BUG/ISSUE] Improper lumped species calculation if missing constituent species

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#80] opened 2020-05-06 01:59 UTC
In GEOS-Chem 12.8.0, the lumped species definition for ISOPN was changed from
```
 ISOPN:
  ISOPNB: 1
  ISOPND: 1
```
to
```
 ISOPN:
  IHN1: 1
  IHN2: 1
  IHN3: 1
  IHN4: 1
```
When comparing GEOS-Chem 12.7.0 and 12.8.0, ISOPN with the new definition should be zero for 12.7.0 because IHN1-4 species do not exist in that version. However, as seen in the 12.8.0 benchmark plots, that is not the case and ISOPN for 12.7.0 is non-zero.
![Screen Shot 2020-05-05 at 9 55 05 PM](https://user-images.githubusercontent.com/4805437/81132208-97175880-8f1b-11ea-9594-40afb8c9f90c.png)
Turning on verbose returns the following output when creating the lumped species for 12.7.0 (Ref):
```
Creating SpeciesConc_ISOPN
Warning: IHN1 needed for ISOPN not in dataset.
Warning: IHN2 needed for ISOPN not in dataset.
Warning: IHN3 needed for ISOPN not in dataset.
Warning: IHN4 needed for ISOPN not in dataset.
```
and 12.8.0 (Dev):
```
Creating SpeciesConc_ISOPN
 -> adding IHN1 with scale 1
 -> adding IHN2 with scale 1
 -> adding IHN3 with scale 1
 -> adding IHN4 with scale 1
```
This suggests that the lumping algorithm is working properly and recognizing that the species that make up ISOPN are not found in 12.7.0 but are found in 12.8.0. This leaves the question as to what is getting plotted for ISOPN in 12.7.0 in the above plot.

**Comment by lizziel** [comment] 2020-05-06 23:37
I took a look at the species lumping in GCPy and identified that there is indeed a bug. For ISOPN in the 12.8 benchmark it shows up because none of the constituent species defined in the lumped species definition file are found in the ref dataset. For the GEOS-Chem 12.8 benchmark this applies to both ISOPN as well as HPALDs. The issue is improper initialization of the new lumped species variable. If no constituent species are found it assigns the last constituent species of the last lumped species defined. For the case of Ref ISOPN the 12.8 benchmark, this was IEPOXD. I implemented a fix and here is the new ISOPN comparison:

<img width="747" alt="Screen Shot 2020-05-06 at 2 00 00 PM" src="https://user-images.githubusercontent.com/651947/81238523-4f9ed400-8fd0-11ea-94fd-097c082289b5.png">

This bug also applied to the case where the first constituent species in the lumped species definition file was missing. This is because proper initialization only occurred if a species was found in the very first iteration of the loop over constituent species. If no species was found in that very first iteration then the new lumped species was initialized to the last constituent species of the last lumped species defined.

This fix is in https://github.com/geoschem/gcpy/commit/8a7c900e3eaa2001d2153747db1984b6f6080fc4 which will be included in GCPy release 0.2.1.

**Closed** 2020-05-06 23:38 UTC
Labels: bug
